# Generated by Django 5.0.2 on 2024-02-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='owner',
            new_name='autor',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='price',
        ),
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='null', upload_to='annonce_image'),
        ),
    ]
