# Generated by Django 5.0.2 on 2024-02-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0003_rename_owner_ad_autor_remove_ad_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='null', upload_to='annonce'),
        ),
    ]
